name: CI Pipeline

on:
  push:
    branches:
      - main
      - staging 

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: INSTALL DEPENDENCIES
        run: yarn install
      - name: GENERATE BUILD
        run: yarn build

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SEMANTIC RELEASE VERSIONING
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
    permissions:
      contents: write

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: SET AWS CREDENTIALS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: DEPLOY MFE @stagepass/app-events
        run: yarn deploy