name: CI Pipeline

on:
  push:
    branches:
      - main
      - staging 

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Generate build
        run: yarn build
      - name: Upload Artifacts 
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
      - name: Install dependencies
        run: yarn install
      - name: Generate build
        run: yarn build
      - name: Semantic Release Versioning
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
    permissions:
      contents: write

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
      - name: Deploye MFE @stagepass/app-events
        run: yarn deploy