name: Deploy MFE @stagepass/app-events

on:
  push: 
    branches:
      - "staging"

jobs: 
  build: 
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: INSTALL DEPENDENCIES
        run: yarn install
      - name: BUILD
        run: yarn build
      - name: SET AWS CREDENTIALS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: DEPLOY APP
        run: yarn deploy
