name: Semantic release 

on:
  push:
    branches:
      - staging
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: INSTALL DEPENDENCIES
        run: yarn install 
      - name: Build app
        run: yarn build 
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
    permissions:
      contents: write
        